name: Run Postman Tests

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "0 16 * * *"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Newman
        run: npm install -g newman newman-reporter-htmlextra

      - name: Run collection
        run: |
          newman run Postman/GYM_E2E_FLOW.postman_collection.json \
            -e Postman/dev.postman_environment.json \
            --env-var "apikey=${{ secrets.API_KEY }}" \
            --reporters cli,htmlextra \
            --reporter-htmlextra-export newman-report/report.html

      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: postman-report
          path: newman-report/
